---
title: "FFAQR Vignette"
author: "Gomez and Nemenov"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Merging Fama/French and AQR Data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This is a package that merges AQR's Quality Minus Junk data set with Fama and French's (FF) portfolio data based on five factors: market returns (less the risk free rate), small minus big, high (book to market) minus low, investment, and operating profitability. The purpose of this package is to clean the data and recommend to the user interesting follow up questions and opportunities for further research.

This package was developed to facilitate further use of the AQR and FF data sets for Econ 20: Quantitative Data Analysis during winter study at Williams College. We would like to thank David Kane and our classmates for their help and guidance.

## Downloading

Use the following commands in an R terminal to install the package:

library(devtools)

install_github("yn1/FFAQR")

library("FFAQR")

?FFAQR

## Package 101

Call updateData() to update all data if up-to-date data is required. Data sets preloaded with package are recent as of 2/6/15. Call updateData("AQR") or updateData("FF") to update only respective data sets. 

Call fetchDf(name) to return updated data (assign to variable with assignment operator).

Example usage:

updateData("AQR")
df <- fetchDf("AQRRF")
View(df)

## Fetch Options

The following is a list of possible arguments for fetchDf(name). 
To be safe, input arguments as strings. 
See below for glossary of acronyms. 
All daily AQR data omitted from suggestions, Java heap runs out of memory when reading file. 



AQRRF - Risk free rate. 

AQRHMLMonthly - Monthly returns for HML factor. 

AQRMKTMonthly - Monthly market returns. 

AQRSMBMonthly - Monthly returns of SMB factor. 

AQRTSMMonthly - Monthly time series momentum returns. 

AQRUMDMonthly - Monthly returns of UMD factor. 



AQRBABFactorsMonthly - Monthly returns for BAB factor. 

AQRBABPortfoliosMonthly - Monthly returns for various BAB portfolios. 



AQRQMJ10QualityBroadGlobal - Monthly returns of 10 global portfolios constructed on quality. 

AQRQMJ10QualityLongUS - Monthly returns of 10 long US portfolios constructed on quality. 

AQRQMJFactorsMonthly - Monthly returns of QMJ factor. 



For the FF data, the name must end with "3", "5", or "10", corresponding to terciles, quintiles, and deciles. That is, if the name is "Equities", you can input "Equities5". 



FFCMAAvgFirmSize - Average firm size used for CMA data. 

FFCMAEqWgtAnn - Equal-weighted annual returns to CMA. 

FFCMAEqWgtMthly - Equal-weighted monthly returns to CMA. 

FFCMANumOfFirms - Number of firms used for CMA data. 

FFCMAValWgtAnn - Value-weighted annual returns to CMA. 

FFCMAValWgtAvgInvAnn - Value-weighted average investment for CMA data. 

FFCMAValWgtMthly - Geometric value-weighted average investment. 



FFHMLAvgFirmSize - Average firm size used for HML data. 

FFHMLEqWgtAnn - Equal-weighted annual returns to HML. 

FFHMLEqWgtDly - Equal-weighted daily returns to HML. 

FFHMLEqWgtMthly - Equal-weighted monthly returns to HML. 

FFHMLNumOfFirms - Number of firms used in HML data. 

FFHMLValWgtAnn - Value-weighted annual returns to HML. 

FFHMLValWgtDly - Value-weighted daily returns to HML. 

FFHMLValWgtMthly - Value-weighted monthly returns to HML. 



FFRMWAvgFirmSize - Average firm size used for RMW data. 

FFRMWEqWgtAnn - Equal-weighted annual returns to RMW. 

FFRMWEqWgtMthly - Equal-weighted monthly returns to RMW. 

FFRMWNumOfFirms - Number of firms used for RMW data. 

FFRMWValWgtAnn - Value-weighted annual returns to RMW. 

FFRMWValWgtAvgOP - Value-weighted average operating profitability. 

FFRMWValWgtMthly - Value-weighted monthly returns to RMW. 



FFSMBAvgFirmSize - Average firm size used for SMB data. 

FFSMBEqWgtAnn - Equal-weighted annual returns to SMB. 

FFSMBEqWgtDly - Equal-weighted daily returns to SMB. 

FFSMBEqWgtMthly - Equal-weighted monthly returns to SMB. 

FFSMBNumOfFirms - Number of firms used in SMB data. 

FFSMBValWgtAnn - Value-weighted annual returns to SMB. 

FFSMBValWgtDly - Value-weighted daily returns to SMB. 

FFSMBValWgtMthly - Value-weighted monthly returns to SMB. 



## Glossary



FF - Fama French 

AQR - AQR 

BAB - Betting Against Beta 

HML - High (Book to Market) Minus Low 

QMJ - Quality Minus Junk 

SMB - Small Minus Big 

TSM - Time Series Momentum 

UMD - Up Minus Down 

CMA - Investment 

RMW - Operating Profitability 



For further information, please visit the original database websites: 

Fama-French:http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html 

AQR: https://www.aqr.com/library/data-sets?page=1 

## Data Sources

FFCMA - Portfolios sorted by investment, monthly.

FFHMLDaily - Portfolios sorted by book to market value, daily.

FFHMLMonthly - Portfolios sorted by book to market value, monthly, includes number of firms and average size of firms included in portfolios.

FFRMW - Portfolios sorted by operating profitability, monthly.

FFSMBDaily - Portfolios sorted by size, daily.

FFSMBMonthly - Portfolios sorted by size, monthly, includes number of firms and average size of firms included in portfolios.

AQRBABDaily - AQR's daily returns on the betting against beta factor.

AQRBABMonthly - AQR's monthly returns on the betting against beta factor.

AQRQMJ10QMonthly - 10 portfolios of US and Global equities (each) sorted by AQR's measure of quality minus junk, monthly.

AQRQMJDaily - AQR's daily returns on the quality minus junk factor.

AQRQMJMonthly - AQR's monthly returns on the quality minus junk factor, includes AQR's returns on portfolios selected through several additional criteria discussed below. For the sake of not downloading the same data multiple times, much of the overlapping AQR data was taken from this data set.

AQRTSMMonthly - AQR's monthly returns to time series momentum.



## Detailed Explanation of Data

Note: The following FF datasets are split into separate subsets that group observations by terciles, quintiles and deciles.

FFCMA

Datasets beginning with FFCMA contain portfolios constructed with respect to investment, which is defined as the change in total assets from the fiscal year ending in year t-2 to the fiscal year ending in t-1, divided by t-1 total assets. It contains value and equal weighted returns for portfolios formed on investment. 

FFHML 

Datasets beginning with FFHML contain portfolios constructed with respect to ratio of book equity to market equity (BE/ME), which is defined as  book equity at the last fiscal year end of the prior calendar year divided by ME at the end of December of the prior year. It contains value and equal weighted returns for portfolios formed on BE/ME. Those datasets that continue as FFHMLDaily contain portfolios that are constructed with daily information, while those that continue as FFHMLMonthly contain portfolios that are constructed with monthly information. Data describing the number of firms and the average size of firms is included for FFHMLMonthly. 

FFRMW

Datasets beginning with FFRMW are constructed with respect to operating profitability, which is defined as operating profits ( sales minus cost of goods sold, minus selling, general, and administrative expenses, minus interests expense) divided by book equity at the last fiscal year end of the prior calendar year. Among these datasets included are those that contain value and equal weighted returns for portfolios. 

FFSMB

Datasets beginning with FFSMB are constructed with respect to the size. SMB or small minus big accounts for the spread between small and large sized firms, which is based on the company’s market capitalization. Among the datasets include are those that contain value and equal weighted returns for portfolios. Additionally, returns by this metric are available as monthly or daily data.  Data describing the number of firms and the average size of firms is included for FFSMBMonthly. 

The following AQR datasets provide AQR's data for returns on several FF factors (including size and book to market), momentum, and the relevant risk free rate.

AQRBABMonthly

Dataset contains monthly excess returns of low-beta stocks over high-beta stocks, as defined my market returns in a universe of both domestic and global equities.

AQRQMJ10QMonthly

Dataset contains monthly returns, in excess of t-bills, of 10 value-weighed, long-only portfolios sorted on quality.  A quality security is defined as one that, all else equal, investors are willing to pay a higher price for: stocks that are safe, well-managed, profitable and growing. It includes 10 quality sorted portfolios, for both a long sample of U.S equities and a broad sample of global equities. It also includes the spread between highest quality portfolio and the lowest quality portfolio. 

AQRQMJMonthly

Dataset contains monthly self-financing excess returns of long/short Quality Minus Junk (QMJ) factors. QMJ is our quality-minus-junk factor that goes long high quality stocks and short low quality stocks. A quality security is defined as one that, all else equal, investors are willing to pay a higher price for: stocks that are safe, well-managed, profitable and growing. QMJ factors are constructed for U.S equities, 23 international equity markets, and multiple aggregates.

AQRTSMMonthly

Data set contains information on time series momentum with regards to equities, currencies, bonds, and commodities. Returns are based on a 12-month time series momentum strategy with a 1-month holding period.

## Troubleshooting Common Errors

Unable to set working directory?
Some functions make use of moving into subdirectories before moving back out into the working directory, please make sure that the project folder is set as the folder directory before attempting to clean or download data.

Unable to import AQR data?
If you cannot run read.xlsx() on the daily AQR data, you need to allocate more memory to your Java heap (see Java's Xmx setting).
